// Code generated by "stringer -type Pixel,Codename,DownloadType -linecomment -output enums_string.go"; DO NOT EDIT.

package pixelimagedl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownDevice-0]
	_ = x[Pixel4-1]
	_ = x[Pixel4XL-2]
	_ = x[Pixel4a-3]
	_ = x[Pixel4a5G-4]
	_ = x[Pixel5-5]
	_ = x[Pixel5a-6]
	_ = x[Pixel6-7]
	_ = x[Pixel6Pro-8]
}

const _Pixel_name = "unknownPixel 4Pixel 4 XLPixel 4aPixel 4a 5GPixel 5Pixel 5aPixel 6Pixel 6 Pro"

var _Pixel_index = [...]uint8{0, 7, 14, 24, 32, 43, 50, 58, 65, 76}

func (i Pixel) String() string {
	if i >= Pixel(len(_Pixel_index)-1) {
		return "Pixel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Pixel_name[_Pixel_index[i]:_Pixel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownCodename-0]
	_ = x[Flame-1]
	_ = x[Coral-2]
	_ = x[Sunfish-3]
	_ = x[Bramble-4]
	_ = x[Redfin-5]
	_ = x[Barbet-6]
	_ = x[Oriole-7]
	_ = x[Raven-8]
}

const _Codename_name = "unknownflamecoralsunfishbrambleredfinbarbetorioleraven"

var _Codename_index = [...]uint8{0, 7, 12, 17, 24, 31, 37, 43, 49, 54}

func (i Codename) String() string {
	if i >= Codename(len(_Codename_index)-1) {
		return "Codename(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Codename_name[_Codename_index[i]:_Codename_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Factory-0]
	_ = x[OTA-1]
}

const _DownloadType_name = "factoryOTA"

var _DownloadType_index = [...]uint8{0, 7, 10}

func (i DownloadType) String() string {
	if i >= DownloadType(len(_DownloadType_index)-1) {
		return "DownloadType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DownloadType_name[_DownloadType_index[i]:_DownloadType_index[i+1]]
}
